max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
use_small_heuristics = true
format_strings = false
wrap_comments = false
comment_width = 80
normalize_comments = false
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Visual"
imports_layout = "Mixed"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = false
reorder_imports_in_group = false
reorder_imported_names = true
binop_separator = "Front"
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
combine_control_expr = true
struct_field_align_threshold = 20
remove_blank_lines_at_start_or_end_of_block = true
match_arm_blocks = true
force_multiline_blocks = false
fn_args_density = "Tall"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
merge_derives = true
use_try_shorthand = false
condense_wildcard_suffixes = false
force_explicit_abi = true
write_mode = "Overwrite"
color = "Auto"
unstable_features = false
disable_all_formatting = false
skip_children = false
error_on_line_overflow = true
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
